config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :cars, only: [:index, :show] do
    resources :reviews, only: :create
    resources :favourites, only: :create
  end

  resources :favourites, only: [:index, :destroy]

  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner
  has_many :reviews
  has_many :favourites
  validates :brand, :model, :year, :fuel, presence: true
  validates :year, numericality: { only_integer: true }
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :car
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cars
  validates :nickname, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  validates :comment, :rating, presence: true
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @review = Review.new
    @favourite = Favourite.new
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @favourites = Favourite.all
  end
  def create
    @favourite = Favourite.new
    @car = Car.find(params[:car_id])
    @favourite.car = @car
      if @favourite.save
        redirect_to car_path(@car)
      else
        render "cars/show", status: unprocessable_entity
      end
  end


  def destroy
    @favourites = Favourites.find(params[:id])
    @favourites.destroy
    redirect_to favourites_path, status: :see_other
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new

  end

  def create
    @car = Car.find(params[:car_id])
    @review = Review.new(review_params)
    @review.car = @car
    if @review.save
      redirect_to car_path(@car)
    else
      render "cars/show", status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cars/index.html.erb
<div class="home">

<h1>My Awesome Garage</h1>

<ul>
<% @cars.each do |car| %>
  <li><%=link_to car.brand, car_path(car) %> - <%=car.model %></li>
<%end %>
</ul>

<div>

app/views/cars/show.html.erb
<div class="container">

<p><%= @car.model %></p>
<p><%= @car.year %></p>
<p><%= @car.fuel %></p>

<div class="form-container">

<h2>Add a new review</h2>
<%= simple_form_for [@car, @review] do |f| %>
  <%= f.input :comment, lebel: false, placeholder: "Comment here..." %>
  <%= f.input :rating, collection: 0..5, lebel: false %>
  <%= f.submit "Add review" %>
<% end %>

</div>
<%= link_to "Go back to all cars", cars_path %>

<h2>All reviews</h2>
<ul>
<% @car.reviews.each do |review| %>
  <li><%= review.comment %> - <%= "🌟" * review.rating %> </li>
<% end %>
</ul>

<% if @car.favourites.empty? %>


<%= simple_form_for [@car, @favourite] do |f| %>
<%= f.submit "Save to my Garage" %>
<% end %>

<% else %>
  <p>This car is in my garage </p>
<% end %>

</div>

app/views/favourites/index.html.erb
<% @favourites.each do |favourite| %>
<p><%= favourite.car.brand %></p>
<p><%= favourite.car.model %></p>
<% link_to favourite_path(favourite), data: {turbo_method: :delete} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <div>
    <head>
      <title>RailsAwesomeGarage</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>
      </head>

    <body>
      <%= render "shared/navbar" %>
      <%= yield %>
    </body>

  </div>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>

<div class="home">
  <h1>My Awesome Garage</h1>
    <%= link_to "See All Cars", cars_path %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img class="avatar" src="https://imageio.forbes.com/specials-images/imageserve/6090f7f251c9c6c605e612fc/0x0.jpg?format=jpg&crop=3127,1759,x0,y33,safe&height=900&width=1600&fit=bounds" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://i.guim.co.uk/img/static/sys-images/Film/Pix/pictures/2013/2/5/1360068404644/Yoda-010.jpg?width=620&dpr=2&s=none"/>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
            </div>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>